# Generated by Django 3.2.9 on 2021-12-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('scowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('msgowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subchannel')),
                ('msguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
