# Generated by Django 3.2.9 on 2022-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_student_banstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=1000)),
                ('newfaculty', models.CharField(max_length=200)),
            ],
        ),
    ]
